// ─────────────────────────────────────────────────────────────────────────────
// TEACHER INVITE COMPLETION SCREEN
// (ISOLATION_ROLES_PLAN.md §11 "Account & access management", §12 step 5,
//  chunk A5 — see modules/admin/teacher-directory.js's "Invite a New
//  Teacher" panel for the admin-side trigger, and
//  supabase/phase37_teacher_invites.sql for the RPCs this calls through
//  TeacherInviteService.)
//
// ENTRY POINT: a link shaped `${origin}${pathname}?teacher_invite=${token}`,
// generated by teacher-directory.js and shared manually by the admin (no
// automated invite email — see phase37's header for why). The IIFE at the
// bottom of this file checks for that query param on every page load and,
// if present, takes over from whatever screen would otherwise show first.
//
// This screen has NO Supabase Auth session requirement to even load — the
// token itself is the only gate (see check_teacher_invite()'s anon grant).
// The person is not logged in and has no profile; this is the one place in
// the app besides the student registration form where that's expected.
// ─────────────────────────────────────────────────────────────────────────────

let _teacherInviteToken = null;

window.showTeacherInviteScreen = async function (token) {
  _teacherInviteToken = token;

  const loginScreen = document.getElementById('login-screen');
  const regScreen = document.getElementById('reg-screen');
  const recoveryScreen = document.getElementById('recovery-screen');
  if (loginScreen) loginScreen.style.display = 'none';
  if (regScreen) regScreen.classList.remove('open');
  if (recoveryScreen) recoveryScreen.classList.remove('open');

  _teacherInviteInjectStyles();
  _teacherInviteRenderLoading();
  document.getElementById('teacher-invite-screen').classList.add('open');

  const result = await TeacherInviteService.checkInvite(token);

  if (!result.ok || !result.valid) {
    _teacherInviteRenderInvalid(!result.ok ? 'error' : result.reason);
    return;
  }

  _teacherInviteRenderForm();
};

function _teacherInviteInjectStyles() {
  if (document.getElementById('teacher-invite-screen-styles')) return;
  const style = document.createElement('style');
  style.id = 'teacher-invite-screen-styles';
  style.textContent = `
    #teacher-invite-screen {
      display: none; position: fixed; inset: 0; z-index: 999;
      background: var(--surface, #1a1a2e);
      overflow-y: auto; padding: 24px 16px;
      justify-content: center; align-items: flex-start;
    }
    #teacher-invite-screen.open { display: flex; }
    .reg-validation-msg { font-size: 11px; min-height: 16px; margin-top: 3px; }
    .reg-validation-msg.ok  { color: #4edea3; }
    .reg-validation-msg.err { color: #ffb4ab; }
  `;
  document.head.appendChild(style);
}

function _teacherInviteRenderLoading() {
  document.getElementById('teacher-invite-card-content').innerHTML = `
    <div style="text-align:center;padding:12px 0">
      <div style="font-family:var(--fh);font-size:28px;font-weight:900">EDUQUEST</div>
      <div style="color:var(--text-muted);font-size:13px;margin:16px 0">Checking your invite link…</div>
    </div>`;
}

const _TEACHER_INVITE_REASON_MSG = {
  not_found: 'This invite link doesn\u2019t exist. Double-check the link your admin sent you.',
  used: 'This invite link has already been used to create an account.',
  revoked: 'This invite link was revoked by an admin.',
  expired: 'This invite link has expired. Ask your admin to generate a new one.',
  error: 'Something went wrong checking this invite link. Please try again.',
};

function _teacherInviteRenderInvalid(reason) {
  const msg = _TEACHER_INVITE_REASON_MSG[reason] || _TEACHER_INVITE_REASON_MSG.error;
  document.getElementById('teacher-invite-card-content').innerHTML = `
    <div class="reg-success-card" style="text-align:center;padding:12px 0">
      <div class="reg-success-icon">\u26a0\ufe0f</div>
      <div class="reg-success-title">Invite link not valid</div>
      <div class="reg-success-sub">${_esc(msg)}</div>
      <button class="btn btn-primary btn-block" style="max-width:260px;margin:0 auto;padding:12px" onclick="hideTeacherInviteScreen()">\u2190 Back to Login</button>
    </div>`;
}

function _teacherInviteRenderForm() {
  document.getElementById('teacher-invite-card-content').innerHTML = `
    <div style="text-align:center;margin-bottom:24px">
      <div style="font-family:var(--fh);font-size:28px;font-weight:900">EDUQUEST</div>
      <div style="color:var(--text-muted);font-size:13px;margin-top:4px">\ud83c\udf93 You\u2019ve been invited as a teacher</div>
    </div>

    <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">
      <div class="form-group" style="margin-bottom:0">
        <label class="form-label">First Name</label>
        <input type="text" id="ti-first" placeholder="Juan" autocomplete="off" style="width:100%">
      </div>
      <div class="form-group" style="margin-bottom:0">
        <label class="form-label">Last Name</label>
        <input type="text" id="ti-last" placeholder="dela Cruz" autocomplete="off" style="width:100%">
      </div>
    </div>

    <div class="form-group" style="margin-top:12px">
      <label class="form-label">Email Address</label>
      <input type="email" id="ti-email" placeholder="juan@example.com" autocomplete="off" style="width:100%">
    </div>

    <div class="form-group">
      <label class="form-label">
        Password <span style="color:var(--text-muted);font-size:11px">(min 8 characters, letters + numbers)</span>
      </label>
      <div style="position:relative">
        <input type="password" id="ti-pass" placeholder="\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022" autocomplete="new-password"
               style="width:100%;padding-right:40px" oninput="teacherInviteCheckValidation()">
        ${regPasswordToggleBtn('ti-pass')}
      </div>
      <div id="ti-pass-msg" class="reg-validation-msg"></div>
    </div>

    <div class="form-group">
      <label class="form-label">Confirm Password</label>
      <div style="position:relative">
        <input type="password" id="ti-pass-confirm" placeholder="\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022" autocomplete="new-password"
               style="width:100%;padding-right:40px" oninput="teacherInviteCheckValidation()"
               onkeydown="if(event.key==='Enter')doCompleteTeacherSignup()">
        ${regPasswordToggleBtn('ti-pass-confirm')}
      </div>
      <div id="ti-pass-confirm-msg" class="reg-validation-msg"></div>
    </div>

    <div id="ti-err" style="color:#ffb4ab;font-size:13px;margin-bottom:10px;display:none"></div>

    <button class="btn btn-primary btn-block" id="ti-submit-btn" style="padding:13px;font-size:15px" onclick="doCompleteTeacherSignup()">
      Create Teacher Account \u2192
    </button>

    <div style="text-align:center;margin-top:16px;font-size:13px;color:var(--text-muted)">
      <a style="color:var(--primary);font-weight:700;cursor:pointer;text-decoration:none" onclick="hideTeacherInviteScreen()">\u2190 Back to Login</a>
    </div>
  `;
  setTimeout(function () { const f = document.getElementById('ti-first'); if (f) f.focus(); }, 50);
}

function teacherInviteCheckValidation() {
  const passEl = document.getElementById('ti-pass');
  const confirmEl = document.getElementById('ti-pass-confirm');
  if (!passEl || !confirmEl) return;
  const pass = passEl.value;
  const confirmVal = confirmEl.value;
  const passMsg = document.getElementById('ti-pass-msg');
  const confirmMsg = document.getElementById('ti-pass-confirm-msg');

  if (!pass) {
    passMsg.textContent = ''; passMsg.className = 'reg-validation-msg';
  } else {
    const v = regValidatePassword(pass);
    passMsg.textContent = v.ok ? '\u2713 Looks good' : v.msg;
    passMsg.className = 'reg-validation-msg ' + (v.ok ? 'ok' : 'err');
  }

  if (!confirmVal) {
    confirmMsg.textContent = ''; confirmMsg.className = 'reg-validation-msg';
  } else {
    const match = confirmVal === pass;
    confirmMsg.textContent = match ? '\u2713 Passwords match' : 'Passwords do not match.';
    confirmMsg.className = 'reg-validation-msg ' + (match ? 'ok' : 'err');
  }
}

window.doCompleteTeacherSignup = async function () {
  const first = document.getElementById('ti-first')?.value.trim() || '';
  const last = document.getElementById('ti-last')?.value.trim() || '';
  const email = (document.getElementById('ti-email')?.value.trim() || '').toLowerCase();
  const pass = document.getElementById('ti-pass')?.value || '';
  const passConfirm = document.getElementById('ti-pass-confirm')?.value || '';
  const err = document.getElementById('ti-err');
  const btn = document.getElementById('ti-submit-btn');

  const errors = [];
  const firstCheck = regValidateName(first, 'First name'); if (!first) errors.push('First name is required.'); else if (!firstCheck.ok) errors.push(firstCheck.msg);
  const lastCheck = regValidateName(last, 'Last name'); if (!last) errors.push('Last name is required.'); else if (!lastCheck.ok) errors.push(lastCheck.msg);
  if (!email || !email.includes('@')) errors.push('Enter a valid email address.');
  const pwCheck = regValidatePassword(pass); if (!pwCheck.ok) errors.push(pwCheck.msg);
  if (pass !== passConfirm) errors.push('Passwords do not match.');

  if (errors.length) {
    err.innerHTML = '\u274c ' + errors.join('<br>\u274c ');
    err.style.display = 'block';
    return;
  }
  err.style.display = 'none';

  const originalLabel = btn.textContent;
  btn.disabled = true; btn.textContent = 'Creating account\u2026';

  const result = await TeacherInviteService.completeSignup({
    token: _teacherInviteToken,
    firstName: first, lastName: last, email: email, password: pass,
    color: regPickColor(email), init: regMakeInitials(first, last),
  });

  btn.disabled = false; btn.textContent = originalLabel;

  if (!result.ok) {
    err.innerHTML = '\u274c ' + _esc(result.error || 'Could not create your account. Please try again.');
    err.style.display = 'block';
    return;
  }

  // Strip the query param now that the token is spent, so a later reload
  // of this same tab/bookmark doesn't re-run the (harmless but pointless)
  // "already used" check on load.
  try {
    const url = new URL(window.location.href);
    url.searchParams.delete('teacher_invite');
    window.history.replaceState({}, '', url.toString());
  } catch (e) {}

  document.getElementById('teacher-invite-card-content').innerHTML = `
    <div class="reg-success-card">
      <div class="reg-success-icon">\u2705</div>
      <div class="reg-success-title">Teacher Account Created!</div>
      <div class="reg-success-sub">Welcome, ${_esc(result.profile.displayName)}. You can log in now with the email and password you just set.</div>
      <button class="btn btn-primary btn-block" style="max-width:260px;margin:0 auto;padding:12px" onclick="hideTeacherInviteScreen()">Go to Login \u2192</button>
    </div>`;
};

window.hideTeacherInviteScreen = function () {
  document.getElementById('teacher-invite-screen').classList.remove('open');
  const loginScreen = document.getElementById('login-screen');
  if (loginScreen) loginScreen.style.display = 'flex';
};

// ── ENTRY POINT — check for ?teacher_invite=<token> on page load ───────────
(function () {
  try {
    const params = new URLSearchParams(window.location.search);
    const token = params.get('teacher_invite');
    if (token) window.showTeacherInviteScreen(token);
  } catch (e) {
    console.warn('[teacher-invite] could not parse invite token from URL:', e);
  }
})();
